version: "3"
services:
  fastpages: &fastpages
    working_dir: /data
    environment:
        - INPUT_BOOL_SAVE_MARKDOWN=false
    build:
      context: ./_action_files
      dockerfile: ./Dockerfile
    image: fastpages-dev
    logging:
      driver: json-file
      options:
        max-size: 50m
    stdin_open: true
    tty: true
    volumes:
      - .:/data/

  converter:
    <<: *fastpages
    command: /fastpages/action_entrypoint.sh

  notebook:
    <<: *fastpages
    command: jupyter notebook --allow-root --no-browser --ip=0.0.0.0 --port=8080 --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - "8080:8080"

  watcher:
    <<: *fastpages
    command: watchmedo shell-command --command /fastpages/action_entrypoint.sh --pattern *.ipynb --recursive --drop
    network_mode: host # for GitHub Codespaces https://github.com/features/codespaces/

  jekyll:
    working_dir: /data
    image: fastai/fastpages-jekyll
    restart: unless-stopped
    ports:
      - "8840:4000"
    volumes:
      - .:/data/
    command: >
      bash -c "chmod -R u+rw . && jekyll serve --host 0.0.0.0 --trace --strict_front_matter"
  
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID} #* 
        - GROUP_ID=${GROUP_ID} #* 
        - USER=${USER_NAME} #*
    ports:
      - "${JUPYTER_PORT}:8888" #*
    expose:
      - "8888"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY} #*
      - GH_TOKEN=${GH_TOKEN} #*
    volumes:
      - ${WORK_PATH}:/home/${USER_NAME}/work #*
      #- ~/.gitconfig:/etc/gitconfig # Need to create this file!
      #- ${LOCAL_DATA_PATH}:/home/${USER_NAME}/data/ #*
